name: Build debian package
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          install_tool="apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes"
          mk-build-deps --install --tool="${install_tool}" debian/control
          gbp buildpackage --git-ignore-branch --git-upstream-tag=debian-pkg -us -uc
          dpkg -I ../freenet*.deb
