name: Build debian package
on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt update
          sudo apt install -y git-buildpackage
          gbp buildpackage --git-upstream-tag=debian-pkg -us -uc
          dpkg -I ../freenet*.deb
