name: Build debian package
on:
  push:
    branches: [ 'master', 'next', 'debian-package' ]
    tags:
      - build**
      - testing-**
jobs:
  build-deb:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        distribution: [temurin]
        java: [17]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          cache: 'gradle'
          distribution: '${{ matrix.distribution }}'
          java-version: '${{ matrix.java }}'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install build-essential debhelper devscripts equivs -y

      - name: Install package build dependencies
        run: |
          install_tool="apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes"
          sudo mk-build-deps --install -r --tool="${install_tool}" debian/control

      - name: Build package
        run: |
          sudo gbp buildpackage --git-ignore-branch --git-upstream-tag=debian-package -us -uc --git-ignore-new || sudo cat /tmp/freenet_0.7.5+*diff*

      - name: Get package info
        run: |
          dpkg -I ../freenet*.deb
          file ../freenet*.deb

